# This is a basic workflow to help you get started with Actions

name: Learn Linux and SSH

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
    # branches: [ main ]
  # pull_request:
    # branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
            inputs:
              OutPutFiles:
                description: 'Output File Name'     
                required: false
                default: 'OutoutFiles'
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Build-OpenWrt"
  Build-OpenWrt:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Installation depends
        run: |
          sudo apt-get update
          mkdir OutputFiles
          mkdir WorkingSpace

      # SSH Connect To Actions
      - name: Setup Debug Session
        uses: csexton/debugger-action@master

      # Upload firmware directory    
      - name: Upload firmware directory
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.OutPutFiles }}
          path: OutputFiles/*

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
