# This is a basic workflow to help you get started with Actions

name: SSH
on:
  workflow_dispatch:
            inputs:
              Outputs:
                description: 'Input Output Name'     
                required: true
                default: 'Outputs'
jobs:
  MyJobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Initalize OS
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E swapoff -a
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /usr/local/lib/android /opt/ghc /swapfile
          sudo -E mkdir ./Outputs
          sudo -E chmod -R 777 Outputs
          sudo -E echo "set nu" > ~/.vimrc
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
      - name: Uploadfiles
        uses: actions/upload-artifact@v3
        with:
          name: MyFiles
          path: ${{ github.workspace }}/Outputs/
