# This is a basic workflow to help you get started with Actions

name: SSH
on:
  workflow_dispatch:
            inputs:
              Outputs:
                description: 'Input Output Name'     
                required: true
                default: 'Outputs'
jobs:
  MyCMD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Initalize OS
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E swapoff -a
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /usr/local/lib/android /opt/ghc /swapfile
          sudo -E mkdir ./Outputs
          sudo -E chmod -R 777 Outputs
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
      - name: Uploadfiles
        uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/Outputs/
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
