# This is a basic workflow to help you get started with Actions

name: SSH
on:
  workflow_dispatch:
            inputs:
              Outputs:
                description: 'Input Output Name'     
                required: true
                default: 'Outputs'
jobs:
  MyJobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initalize OS
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E swapoff -a
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /usr/local/lib/android /opt/ghc /swapfile
          sudo -E mkdir ./Outputs
          sudo -E chmod -R 777 Outputs
          sudo -E cp ${{ github.workspace }}/.vimrc ~/

      - name: First Setup Debug Session
        uses: P3TERX/ssh2actions@main
      
      - name: make auto
        run: |
          sudo -E cd ${{ github.workspace }}/openwrt/
          sudo -E make V=s -j$(nproc)

      - name: Last Setup Debug Session
        uses: P3TERX/ssh2actions@main

      - name: Uploadfiles
        uses: actions/upload-artifact@v3
        with:
          name: MyFiles
          path: ${{ github.workspace }}/Outputs/
